# Site settings
title: "Carol Rose, Actress"
email: carol@carolroseactress.com
description: > # this means to ignore newlines until "baseurl:"
  Carol is a Chicago-based actress.
baseurl: "/carolroseactress.com" # the subpath of your site, e.g. /blog/
url: "http://happycollision.github.io" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['smart']

permalink: pretty

exclude:
  - .bowerrc
  - .gitignore
  - bower.json
  
defaults:
-
  scope:
    path: "pages"
    type: "pages"
  values:
    layout: "page"
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
    
prose:
  siteurl: 'http://happycollision.github.io/carolroseactress.com/'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      # - name: "splash"
      #   field:
      #     element: "text"
      #     label: "Splash image"
      #     value: ""
    # _posts/static:
    #   - name: "layout"
    #     field:
    #       element: "hidden"
    #       value: "page"
    #   - name: "title"
    #     field:
    #       element: "text"
    #       label: "Title"
    #       value: ""
    #   - name: "permalink"
    #     field:
    #       element: "text"
    #       label: "Permalink"
    #       value: ""
